- name: Update apt repository
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Manage apt updates, upgrades, and package installation
  shell: |
    while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done
    apt-get update && apt-get dist-upgrade -y
    apt-get install -y unattended-upgrades
    apt-get autoremove -y
    apt-get autoclean -y

- name: Configure Unattended Upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Package-Blacklist {};
      Unattended-Upgrade::DevRelease "auto";
      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}-security";
      };
    owner: root
    group: root
    mode: '0644'
